### ISSUE TITLE
Document the setup required in order to run auto-pts with Zephyr

### ISSUE THREAD

**Issue by michal-narajowski** [codecoup/auto-pts#1]
In the official Zephyr documentation, as .rst), in terms of hardware required and the software installation/setup steps necessary.

https://github.com/zephyrproject-rtos/zephyr/tree/master/doc/guides/bluetooth

**Comment by mkasenberg** [comment]
- [x] Windows 10 setup
- [ ] Linux with Windows 10 virtual machine setup

https://github.com/codecoup/zephyr/pull/1
