### ISSUE TITLE
Allow collection of btmon logs from the RTT buffer

### ISSUE THREAD

**Issue by mkasenberg** [codecoup/auto-pts#19]
- [x] Implement the option to write btmon logs to the RTT buffer in Zephyr. 
- [x] Implement reading and saving btmon logs in AutoPTS.(just Linux for now)

https://github.com/codecoup/zephyr/pull/2
https://github.com/codecoup/auto-pts/pull/10

**Comment by michal-narajowski** [comment]
Is this https://github.com/intel/auto-pts/pull/501 required to finish this issue?

**Comment by mkasenberg** [comment]
It removes use of rtt2pty, so I think we can close this issue.
