### ISSUE TITLE
Update the ICS documents in the Zephyr documentation

### ISSUE THREAD

**Issue by michal-narajowski** [codecoup/auto-pts#2]

**Comment by KKopyscinski** [comment]
Tests that are in test plan but not in PTS:
GAP/CONN/ACEP/BV-03-C
GAP/CONN/ACEP/BV-04-C
GAP/CONN/DCEP/BV-05-C
GAP/CONN/DCEP/BV-06-C
GAP/CONN/GCEP/BV-05-C
GAP/CONN/GCEP/BV-06-C

PTS workspace has enabled L2CAP/ECFC/BV-19-C, but it's not in test plan - it should be added, as per [TSE](https://www.bluetooth.org/tse/errata_view.cfm?errata_id=13405)

**Comment by KKopyscinski** [comment]
@michal-narajowski should Mesh Models be added to this Test Plan?

**Comment by KKopyscinski** [comment]
Following tests are not implemented:
<details>

 75/601   GAP     GAP/SEC/SEM/BV-21-C           NOT_IMPLEMENTED 0.0                  
 76/601   GAP     GAP/SEC/SEM/BV-37-C           NOT_IMPLEMENTED 0.0                  
 77/601   GAP     GAP/SEC/SEM/BV-38-C           NOT_IMPLEMENTED 0.0                  
 78/601   GAP     GAP/SEC/SEM/BV-22-C           NOT_IMPLEMENTED 0.0                  
 79/601   GAP     GAP/SEC/SEM/BV-39-C           NOT_IMPLEMENTED 0.0                  
 80/601   GAP     GAP/SEC/SEM/BV-40-C           NOT_IMPLEMENTED 0.0                  
 81/601   GAP     GAP/SEC/SEM/BV-23-C           NOT_IMPLEMENTED 0.0                  
 82/601   GAP     GAP/SEC/SEM/BV-24-C           NOT_IMPLEMENTED 0.0                  
 83/601   GAP     GAP/SEC/SEM/BI-09-C           NOT_IMPLEMENTED 0.0                  
 84/601   GAP     GAP/SEC/SEM/BI-10-C           NOT_IMPLEMENTED 0.0                  
 85/601   GAP     GAP/SEC/SEM/BV-26-C           NOT_IMPLEMENTED 0.0                  
 86/601   GAP     GAP/SEC/SEM/BV-41-C           NOT_IMPLEMENTED 0.0                  
 87/601   GAP     GAP/SEC/SEM/BV-42-C           NOT_IMPLEMENTED 0.0                  
 88/601   GAP     GAP/SEC/SEM/BV-27-C           NOT_IMPLEMENTED 0.0                  
 89/601   GAP     GAP/SEC/SEM/BV-43-C           NOT_IMPLEMENTED 0.0                  
 90/601   GAP     GAP/SEC/SEM/BV-44-C           NOT_IMPLEMENTED 0.0                  
 91/601   GAP     GAP/SEC/SEM/BV-28-C           NOT_IMPLEMENTED 0.0                  
 92/601   GAP     GAP/SEC/SEM/BV-29-C           NOT_IMPLEMENTED 0.0                  
245/601   L2CAP   L2CAP/COS/ECFC/BV-01-C        NOT_IMPLEMENTED 0.0                  
246/601   L2CAP   L2CAP/COS/ECFC/BV-02-C        NOT_IMPLEMENTED 0.0                  
247/601   L2CAP   L2CAP/COS/ECFC/BV-03-C        NOT_IMPLEMENTED 0.0                  
264/601   L2CAP   L2CAP/LE/CFC/BV-10-C          NOT_IMPLEMENTED 0.0                  
266/601   L2CAP   L2CAP/LE/CFC/BV-12-C          NOT_IMPLEMENTED 0.0                  
267/601   L2CAP   L2CAP/LE/CFC/BV-13-C          NOT_IMPLEMENTED 0.0                  
269/601   L2CAP   L2CAP/LE/CFC/BV-15-C          NOT_IMPLEMENTED 0.0                  
275/601   L2CAP   L2CAP/ECFC/BV-01-C            NOT_IMPLEMENTED 0.0                  
276/601   L2CAP   L2CAP/ECFC/BV-02-C            NOT_IMPLEMENTED 0.0                  
277/601   L2CAP   L2CAP/ECFC/BV-03-C            NOT_IMPLEMENTED 0.0                  
278/601   L2CAP   L2CAP/ECFC/BV-04-C            NOT_IMPLEMENTED 0.0                  
279/601   L2CAP   L2CAP/ECFC/BV-06-C            NOT_IMPLEMENTED 0.0                  
280/601   L2CAP   L2CAP/ECFC/BV-07-C            NOT_IMPLEMENTED 0.0                  
281/601   L2CAP   L2CAP/ECFC/BI-01-C            NOT_IMPLEMENTED 0.0                  
282/601   L2CAP   L2CAP/ECFC/BI-02-C            NOT_IMPLEMENTED 0.0                  
283/601   L2CAP   L2CAP/ECFC/BV-08-C            NOT_IMPLEMENTED 0.0                  
284/601   L2CAP   L2CAP/ECFC/BV-09-C            NOT_IMPLEMENTED 0.0                  
285/601   L2CAP   L2CAP/ECFC/BV-10-C            NOT_IMPLEMENTED 0.0                  
286/601   L2CAP   L2CAP/ECFC/BV-11-C            NOT_IMPLEMENTED 0.0                  
287/601   L2CAP   L2CAP/ECFC/BV-12-C            NOT_IMPLEMENTED 0.0                  
288/601   L2CAP   L2CAP/ECFC/BV-13-C            NOT_IMPLEMENTED 0.0                  
289/601   L2CAP   L2CAP/ECFC/BV-14-C            NOT_IMPLEMENTED 0.0                  
290/601   L2CAP   L2CAP/ECFC/BV-15-C            NOT_IMPLEMENTED 0.0                  
291/601   L2CAP   L2CAP/ECFC/BV-16-C            NOT_IMPLEMENTED 0.0                  
292/601   L2CAP   L2CAP/ECFC/BV-17-C            NOT_IMPLEMENTED 0.0                  
293/601   L2CAP   L2CAP/ECFC/BV-18-C            NOT_IMPLEMENTED 0.0                  
294/601   L2CAP   L2CAP/ECFC/BV-19-C            NOT_IMPLEMENTED 0.0                  
295/601   L2CAP   L2CAP/ECFC/BV-20-C            NOT_IMPLEMENTED 0.0                  
296/601   L2CAP   L2CAP/ECFC/BV-21-C            NOT_IMPLEMENTED 0.0                  
297/601   L2CAP   L2CAP/ECFC/BV-22-C            NOT_IMPLEMENTED 0.0                  
298/601   L2CAP   L2CAP/ECFC/BV-23-C            NOT_IMPLEMENTED 0.0                  
299/601   L2CAP   L2CAP/ECFC/BI-03-C            NOT_IMPLEMENTED 0.0                  
300/601   L2CAP   L2CAP/ECFC/BV-24-C            NOT_IMPLEMENTED 0.0                  
301/601   L2CAP   L2CAP/ECFC/BV-25-C            NOT_IMPLEMENTED 0.0                  
302/601   L2CAP   L2CAP/ECFC/BI-04-C            NOT_IMPLEMENTED 0.0                  
303/601   L2CAP   L2CAP/ECFC/BV-26-C            NOT_IMPLEMENTED 0.0                  
304/601   L2CAP   L2CAP/ECFC/BV-27-C            NOT_IMPLEMENTED 0.0                  
305/601   L2CAP   L2CAP/ECFC/BI-05-C            NOT_IMPLEMENTED 0.0                  
306/601   L2CAP   L2CAP/ECFC/BI-06-C            NOT_IMPLEMENTED 0.0                  
392/601   MESH    MESH/NODE/FRND/FN/BV-01-C     NOT_IMPLEMENTED 0.0                  
393/601   MESH    MESH/NODE/FRND/FN/BV-02-C     NOT_IMPLEMENTED 0.0                  
394/601   MESH    MESH/NODE/FRND/FN/BV-03-C     NOT_IMPLEMENTED 0.0                  
395/601   MESH    MESH/NODE/FRND/FN/BV-04-C     NOT_IMPLEMENTED 0.0                  
396/601   MESH    MESH/NODE/FRND/FN/BV-05-C     NOT_IMPLEMENTED 0.0                  
397/601   MESH    MESH/NODE/FRND/FN/BV-06-C     NOT_IMPLEMENTED 0.0                  
398/601   MESH    MESH/NODE/FRND/FN/BV-07-C     NOT_IMPLEMENTED 0.0                  
399/601   MESH    MESH/NODE/FRND/FN/BV-08-C     NOT_IMPLEMENTED 0.0                  
400/601   MESH    MESH/NODE/FRND/FN/BV-09-C     NOT_IMPLEMENTED 0.0                  
401/601   MESH    MESH/NODE/FRND/FN/BV-10-C     NOT_IMPLEMENTED 0.0                  
402/601   MESH    MESH/NODE/FRND/FN/BV-11-C     NOT_IMPLEMENTED 0.0                  
403/601   MESH    MESH/NODE/FRND/FN/BV-12-C     NOT_IMPLEMENTED 0.0                  
404/601   MESH    MESH/NODE/FRND/FN/BV-13-C     NOT_IMPLEMENTED 0.0                  
405/601   MESH    MESH/NODE/FRND/FN/BV-14-C     NOT_IMPLEMENTED 0.0                  
406/601   MESH    MESH/NODE/FRND/FN/BV-15-C     NOT_IMPLEMENTED 0.0                  
407/601   MESH    MESH/NODE/FRND/FN/BV-16-C     NOT_IMPLEMENTED 0.0                  
408/601   MESH    MESH/NODE/FRND/FN/BV-17-C     NOT_IMPLEMENTED 0.0                  
409/601   MESH    MESH/NODE/FRND/FN/BV-18-C     NOT_IMPLEMENTED 0.0                  
410/601   MESH    MESH/NODE/FRND/FN/BV-19-C     NOT_IMPLEMENTED 0.0                  
411/601   MESH    MESH/NODE/FRND/FN/BV-20-C     NOT_IMPLEMENTED 0.0                  
412/601   MESH    MESH/NODE/FRND/FN/BV-21-C     NOT_IMPLEMENTED 0.0                  
415/601   MESH    MESH/NODE/FRND/FN/BI-01-C     NOT_IMPLEMENTED 0.0                  
416/601   MESH    MESH/NODE/FRND/FN/BI-02-C     NOT_IMPLEMENTED 0.0                  
417/601   MESH    MESH/NODE/FRND/FN/BI-03-C     NOT_IMPLEMENTED 0.0                  
430/601   MESH    MESH/SR/PROX/BV-02-C          NOT_IMPLEMENTED 0.0                  
431/601   MESH    MESH/SR/PROX/BV-03-C          NOT_IMPLEMENTED 0.0                  
432/601   MESH    MESH/SR/PROX/BV-04-C          NOT_IMPLEMENTED 0.0                  
433/601   MESH    MESH/SR/PROX/BV-05-C          NOT_IMPLEMENTED 0.0                  
434/601   MESH    MESH/SR/PROX/BV-06-C          NOT_IMPLEMENTED 0.0                  
436/601   MESH    MESH/SR/PROX/BV-08-C          NOT_IMPLEMENTED 0.0                  
437/601   MESH    MESH/SR/PROX/BV-09-C          NOT_IMPLEMENTED 0.0                  
438/601   MESH    MESH/SR/PROX/BV-10-C          NOT_IMPLEMENTED 0.0                  
440/601   MESH    MESH/SR/PROX/BV-12-C          NOT_IMPLEMENTED 0.0                  
441/601   MESH    MESH/SR/PROX/BV-13-C          NOT_IMPLEMENTED 0.0                  
442/601   MESH    MESH/SR/PROX/BV-14-C          NOT_IMPLEMENTED 0.0                  
444/601   MESH    MESH/SR/PROX/BI-01-C          NOT_IMPLEMENTED 0.0                  
512/601   MESH    MESH/NODE/CFG/HBP/BV-05-C     NOT_IMPLEMENTED 0.0                  
521/601   MESH    MESH/NODE/CFG/HBS/BV-05-C     NOT_IMPLEMENTED 0.0                  
NOT_IMPLEMENTED      95


<details/>

**Comment by KKopyscinski** [comment]
Commit with updated ICS was merged
